zincware/ZnTrack

zntrack/zn/__init__.py
In #98 the feature for `zn.plots()` was merged.
This feature was not ready to be pushed to main yet and has to be fixed according to #116 
This PR will disable the feature until it is fixed.
=> Disable untested `zn.plots` feature

zntrack/core/zntrack.py, zntrack/utils/config.py
Add the possibility to not write a dvc file after the `__call__`.
This can be useful, e.g. for tests
=> Add config option `no_dvc`

CI/integration_tests/test_exec_node.py, docs/source/_overview/OptionalDVC.ipynb, docs/source/index.rst, zntrack/core/data_classes.py, zntrack/core/decorator.py, zntrack/core/zntrack.py
- move dvc arguments to new dataclass, to support more options dynamically
- renamed `exec_` to `no_exec: bool = True` in accordance with the official naming conventions. 
**THIS IS AN API CHANGE!** Depreciation Warning is added
- add support for `--external` and `--no-commit`
Add the `--external` argument to `dvc run` via
```py
@Node(external=True, no_commit=True)
class HelloWorld(TypeHintParent):
dvc.outs("/work/remote_data")
```
Alternative would be to import the dataclass  directly, but I think I'll stick with the arguments, although this means writing code twice.
```py
from zntrack import DVCOptions
@Node(DVCOptions(force=True, no_run_cache=True, external=True))
class HelloWorld(TypeHintParent):
dvc.outs("/work/remote_data")
```
=> Add Support for missing DVC Options

tests/integration_tests/test_single_node.py, zntrack/core/dvcgraph.py
In addition to `write_graph(no_exec=False)` it is now possible to use `write_graph(run=True)`.
Because `exec` is a Python built-in it was replaced by `run`.
=> add run argument in addition to `no_exec`

.github/workflows/pytest.yaml, setup.py, tests/integration_tests/interface/test_base_interface.py, zntrack/interface/base.py
This PR shows the issues with Python 3.7 and 3.6 in the test runs.
I will try to fix the issues for the windows CI and make ZnTrack compatible with Python 3.7.
Since Python 3.6 reached its end of life it will not be supported.
=> Support Python 3.7

examples/docs/03_dependencies.ipynb, tests/integration_tests/test_node_to_node_dependencies.py, tests/unit_tests/core/test_core_base.py, zntrack/core/base.py, zntrack/core/dvcgraph.py, zntrack/core/zntrackoption.py, zntrack/dvc/__init__.py, zntrack/utils/utils.py, zntrack/zn/__init__.py
To avoid loading a class as da dependency it is now possible to use
```py
deps = zn.deps(SomeNode)
deps = zn.deps(SomeNode.load())
```
This avoids loading `SomeNode` upon class definition and only load the class in the `__init__`. It does not work with `load(name=...)` or `load(lazy=...)`.
=> Allow for class dependencies

zntrack/core/jupyter.py
Currently the full notebook is converted into a `*.py` file.
With this change you can add `# zntrack: break` to stop converting the Notebook into a `*.py` file, if the Node that the conversion triggered was already found.
=> Stop converting jupyter to python after class definition is found

tests/integration_tests/test_single_node.py, zntrack/core/base.py, zntrack/utils/utils.py
This PR introduces an additonal syntex to load a Node via:
```py
class MyNode(Node):
pass
my_node = MyNode["nodename"]
my_node = MyNode[{"name": "nodename"}]
```
=> Allow `Node[<nodename>]` to load a Node

.github/workflows/lint.yaml, .github/workflows/pytest.yaml, pyproject.toml, tests/integration_tests/test_single_node.py, tests/integration_tests/test_zn_deps.py, tests/integration_tests/test_zn_methods.py, tests/unit_tests/core/test_core_base.py, tests/unit_tests/utlis/test_helpers.py, zntrack/__init__.py, zntrack/core/base.py, zntrack/core/jupyter.py, zntrack/core/zntrackoption.py, zntrack/dvc/__init__.py, zntrack/metadata/base.py, zntrack/utils/exceptions.py, zntrack/utils/helpers.py, zntrack/utils/serializer.py, zntrack/utils/utils.py, zntrack/zn/__init__.py, zntrack/zn/method.py, zntrack/zn/split_option.py
- Add `perflint` to the CI
- remove `Node[(name, lazy)]` tuple access and restrict to name / dict
- raise error when passing a Node to `zn.Method`
=> Pylint perflint

examples/docs/01_Intro.ipynb, examples/docs/03_dependencies.ipynb, examples/docs/06_named_nodes.ipynb, examples/docs/09_lazy.ipynb, tests/integration_tests/test_node_to_node_dependencies.py, tests/unit_tests/zn/test_zn_options.py, zntrack/__init__.py, zntrack/core/dvcgraph.py, zntrack/utils/helpers.py, zntrack/utils/serializer.py, zntrack/zn/__init__.py, zntrack/zn/dependencies.py
This PR allows you to directly depend on other nodes attributes and not only rely on the full Node.
```py
class Node1(Node):
outs: int = zn.outs()
class Node2(Node):
node_1_outs: int = zn.deps(getdeps(Node1, "outs"))
node_1_outs: int = zn.deps(getdeps(Node1.load(name="nodename"), "outs"))
node_1_outs: int = zn.deps(getdeps(Node1["nodename"], "outs"))
```
=> Allow for Node Attribute dependencies

examples/docs/03_dependencies.ipynb, tests/integration_tests/test_getdeps.py, tests/unit_tests/core/test_core_base.py, zntrack/core/base.py, zntrack/zn/dependencies.py
In addition to `getdeps(Node, "attribute")` you can now use `Node @ "attribute"` without the need of importing `from zntrack import getdeps`.
This allows users who prefer the `@` shorthand to use that. For the documentation the usage of `getdeps` should be prefered, because it better shows what is happening.
=> Add matmul shorthand

examples/docs/02_PassingClasses.ipynb, tests/integration_tests/test_inheritance.py, tests/integration_tests/test_single_node.py, tests/unit_tests/core/test_core_base.py, tests/unit_tests/core/test_dvcgraph.py, tests/unit_tests/descriptor/test_descriptor.py, tests/unit_tests/utlis/test_utils.py, zntrack/core/base.py, zntrack/core/dvcgraph.py, zntrack/core/zntrackoption.py, zntrack/descriptor/__init__.py, zntrack/dvc/__init__.py, zntrack/utils/file_io.py, zntrack/utils/utils.py, zntrack/zn/__init__.py
=> Fix Inheritance Issue

tests/integration_tests/test_zn_plots.py, zntrack/zn/plots.py
set `df.index.name="index"` if no index is provided to work with DVC.
fix #261
=> Generate `df.index.name` if not provided

setup.py, tests/integration_tests/test_zn_plots.py, zntrack/__init__.py, zntrack/core/base.py, zntrack/core/dvcgraph.py, zntrack/utils/structs.py, zntrack/zn/plots.py
You can now call `save_plots()` in a Node to update all `zn.plots()` similar to DVC Live
=> add `save_plots` and introduce new `ZnTypes.PLOTS`

examples/docs/01_Intro.ipynb, tests/integration_tests/examples/test_example_02.py, tests/integration_tests/interface/test_base_interface.py, tests/integration_tests/test_dvc_params.py, tests/unit_tests/core/test_dvcgraph.py, zntrack/core/dvcgraph.py, zntrack/core/jupyter.py, zntrack/dvc/__init__.py
* remove old functionality from `dvc.params` to map `zn.params`
* use `dvc.params` to add files as parameters.
=> change `dvc.params` to work with files

examples/docs/05_metadata.ipynb, tests/integration_tests/test_timeit.py, zntrack/metadata/base.py, zntrack/metadata/decorators.py
=> add mean/std to timeit decorator

tests/integration_tests/test_single_node.py, zntrack/core/zntrackoption.py
Allows e.g. `zn,outs(filename="custom_data")` to store the outs of this specific option not in `outs.json` but in `custom_data.json`.
=> add `filename` kwargs

tests/integration_tests/test_single_node.py, tests/unit_tests/core/test_dvcgraph.py, tests/unit_tests/descriptor/test_descriptor.py, zntrack/core/base.py, zntrack/core/dvcgraph.py, zntrack/core/zntrackoption.py, zntrack/descriptor/__init__.py, zntrack/dvc/__init__.py, zntrack/zn/__init__.py, zntrack/zn/method.py
- Add `Node.zntrack` property which can not be overwritten.
- add `Node.zntrack.collect(<ZnTrackOption>)`
```py
class ExampleNode01(Node):
inputs = zn.params()
outputs = zn.outs()
ExampleNode01(inputs="Hello World").write_graph(run=True)
ExampleNode01.load().zntrack.collect(zn.params) == {"inputs": "Hello World"}
```
for more examples checkout the tests.
=> add `zntrack.collect` as Node attribute

examples/docs/03_dependencies.ipynb, poetry.lock, pyproject.toml, tests/integration_tests/test_dvc_outs.py, zntrack/core/zntrackoption.py, zntrack/dvc/__init__.py, zntrack/dvc/custom_base.py, zntrack/utils/utils.py
- partially address #226
- allow dvc.<...> to store results in a dedicated node directory
- split `__get__`
- small bugfix with auto_init and super_init call
=> add `use_node_dir` to save results in the nodes directory

poetry.lock, tests/conftest.py, tests/integration_tests/examples/test_example_01.py, tests/integration_tests/examples/test_example_02.py, tests/integration_tests/examples/test_example_03.py, tests/integration_tests/examples/test_example_04.py, tests/integration_tests/examples/test_example_05.py, tests/integration_tests/function_wrapper/test_func_func_deps.py, tests/integration_tests/function_wrapper/test_func_node_deps.py, tests/integration_tests/function_wrapper/test_single_function.py, tests/integration_tests/interface/test_base_interface.py, tests/integration_tests/test_dvc_checkpoints.py, tests/integration_tests/test_dvc_outs.py, tests/integration_tests/test_dvc_params.py, tests/integration_tests/test_file_changes.py, tests/integration_tests/test_getdeps.py, tests/integration_tests/test_inheritance.py, tests/integration_tests/test_lazy_loading.py, tests/integration_tests/test_node_to_node_dependencies.py, tests/integration_tests/test_options_save_n_load.py, tests/integration_tests/test_single_node.py, tests/integration_tests/test_timeit.py, tests/integration_tests/test_zn_deps.py, tests/integration_tests/test_zn_methods.py, tests/integration_tests/test_zn_nodes2.py, tests/integration_tests/test_zn_params.py, tests/integration_tests/test_zn_plots.py, tests/integration_tests/various_tests.py
- add `conftest.pyt`
- run `poetry update`
=> Cleanup `proj_path` fixture

tests/integration_tests/test_zn_nodes2.py, zntrack/zn/nodes.py
Hydra does not support
`dvc exp run --queue -S "my-param=10"`
but only
`dvc exp run --queue -S "my_param=10"`
so we replace it for `zn.Nodes`
=> use `_` instead of `-` as delimiter

tests/unit_tests/utils/test_nwd.py, zntrack/utils/nwd.py
Allow `dvc.outs(zntrack.nwd)` directly without requiring `zntrack.nwd / <...>`
=> improve `nwd`

tests/integration/test_meta.py, zntrack/cli/__init__.py, zntrack/fields/meta/__init__.py, zntrack/project/zntrack_project.py, zntrack/utils/config.py
The `env.yaml` has been extended:
```yaml
global:  # support for global envs on all stages
ZNTRACK_EXAMPLE: '1'
stages:
EnvAsDict:
SPECIAL_ENV: '25'
env:  # you can group envs now
OMP_NUM_THREADS: '1'
```
- support for groups `zntrack.meta.Environement: dict`
- support for global `project.run(environment: dict = ...)`
=> Improve `zntrack.meta.Environement`

poetry.lock, pyproject.toml, tests/integration/test_dvc_plots.py, zntrack/fields/dvc/__init__.py, zntrack/fields/field.py, zntrack/fields/zn/__init__.py
- tests
- support `zn.plots`
- allow multiple plots from the same data source (consider https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#plots) over `dvc plots modify`. Maybe via `y = [loss, mae]`
- requires DVC `2.53.1` or later
=> Add plots modify

tests/integration/test_misc.py, zntrack/utils/__init__.py
Allow
```python
class CustomModule(zntrack.Node):
_module_ = "zntrack.nodes"
```
to define the `__module__` to import from, altough the Node might be defined somewhere else.
This is useful if:
- your package has a lot of Nodes in differente modules, to organize them
- you want to be able to rename the modules
- you have one import for all nodes `package.nodes.<my_node>`
=> allow _module_ to define custom import path

tests/integration/test_single_node.py, zntrack/fields/zn/__init__.py, zntrack/project/zntrack_project.py
You can do `Node.from_rev()` and access parameters.
If they are not present in `params.yaml` they will default to None instead of raising an exception.
=> Params loading

.pre-commit-config.yaml, README.md, tests/integration/test_from_rev.py, tests/integration/test_project.py, tests/integration/test_single_node.py, zntrack/__init__.py, zntrack/core/load.py
=> 628 reconstruct node from dvcyaml

examples/docs/02_Inheritance.ipynb, poetry.lock, pyproject.toml, tests/integration/test_node_nwd.py, tests/unit_tests/test_zn_deps.py, zntrack/cli/__init__.py, zntrack/core/node.py, zntrack/fields/dvc/__init__.py, zntrack/fields/zn/__init__.py
This PR will require an update of all Nodes:
1. Rewrite the Graph
2. `zntrack run ipsuite.nodes.LangevinThermostat --name <node-name> --uuid-only`
3. `dvc commit nodes/<node-name>/uuid`
Otherwise, the stage will not load be rerun!
Furthermore, it is no longer possible to have:
```
zntrack.dvc.outs(zntrack.nwd)
```
but only 
```
zntrack.dvc.outs(zntrack.nwd/<your file or path>)
```
=> `Breaking Update` Add UUID output to every Node

tests/integration/test_project.py, tests/integration/test_zn_nodes2.py, zntrack/core/node.py, zntrack/fields/field.py, zntrack/fields/zn/__init__.py, zntrack/project/zntrack_project.py
This option integrated:
```
The DVC graph relies on file outputs for connecting stages.
ZnTrack will use a '--outs' for each stage by default.
This will require a DVC remote to be setup.
If a project is not used with a DVC remote and strictly GIT,
this can be set to True and instead '--metrics-no-cache' will be used.
Metrics is used instead of 'outs-no-cache' to keep the DVC run cache.
```
=> Add `Project(git_only_repo: bool)`

pyproject.toml, tests/integration/test_cli.py, tests/integration/test_external_experiments.py, tests/integration/test_from_rev.py, tests/integration/test_lazy_loading.py, tests/integration/test_list_deps.py, tests/integration/test_node_node.py, tests/integration/test_project.py, tests/integration/test_single_node.py, tests/integration/test_zn_plots.py, zntrack/examples/__init__.py
Add `from zntrack import examples` to have some example Nodes, primarily used for testing.
- exclude examples from codecov?
=> add example module

tests/integration/test_project.py, zntrack/project/zntrack_project.py
Can now do:
```python
project = zntrack.Project(automatic_node_names=True)
with project.group("AL0") as al_0:
node_1 = zntrack.examples.ParamsToOuts(params="Lorem Ipsum")
```
=> open graph directly

README.md, tests/integration/test_cli.py, tests/integration/test_get_nodes.py, zntrack/__init__.py, zntrack/cli/__init__.py, zntrack/core/load.py, zntrack/utils/cli.py
Add the CLI `zntrack list <remote> <rev>` to list all ZnTrack Nodes for the given revision.
```bash
> zntrack list https://github.com/IPSProjects/SDR.git ethanol
nodes:
- SmilesToAtoms
- Packmol
- CP2KSinglePoint
- EtOH-x10
```
Add `zntrack.get_nodes(remote, rev) -> dict[str, Node]` to gather all Nodes from a given remote.
=> Add `zntrack list` and `zntrack.get_nodes`

pyproject.toml, tests/integration/test_dvc_outs.py, tests/test_zntrack.py, zntrack/core/node.py, zntrack/examples/__init__.py, zntrack/fields/dvc/options.py, zntrack/utils/__init__.py, zntrack/utils/config.py
In addition to:
```python
return self.state.fs.read_text(self.outs)
```
you can now use an actual directory through, for tools that do not support the `DVCFileSystem`
```python
with self.state.use_tmp_paths():
return self.outs.read_text()
```
- How to avoid using the  temporary directory, if the data already exists within the cwd?
- loading multiple `*_path`
- what if the `*_path` is a list / dict / ... ?
- could this be a `from_rev` or `load` feature? Where you run:
```py
with zntrack.from_rev(node, use_tmp_path=True):
...
```
`use_tmp_path` vs `use_tmp_paths` ?
=> Access `*_path` with `node.use_tmp_paths`

tests/integration/test_project.py, zntrack/project/zntrack_project.py
Fixes #773 by adding support for
```python
assert list(group_1) == [node_1, node_2]
group_1["ParamsToOuts"] == node_1
group_1["Group1_ParamsToOuts"] == node_1
"Group1_ParamsToOuts" in group_1
"ParamsToOuts" in group_1
```
=> Support `__getitem__` for Groups

tests/integration/test_apply.py, zntrack/__init__.py, zntrack/cli/__init__.py, zntrack/core/node.py, zntrack/examples/__init__.py, zntrack/project/zntrack_project.py, zntrack/utils/apply.py
This method allows you to customize which method should be executed by DVC / the graph.
```py
JoinedParamsToOuts = zntrack.apply(zntrack.examples.ParamsToOuts, "join")
```
will run `ParamsToOuts.join` instead of `ParamsToOuts.run`.
=> add `zntrack.apply`

tests/integration/test_apply.py, zntrack/examples/__init__.py
It was unclear if using a `zntrack.apply` `Node` as a dependency works, this PR shows that it does.
=> Add more tests for `zntrack.apply`
