- .github/FUNDING.yml
- README.rst
- docs/source/Overview/PassingClasses.ipynb
* added doc strings to the tutorial
* Fixed up the links in the readme
> Sam tov minor updates

- .github/workflows/pytest.yaml
- CI/integration_tests/dependencies/test_node_to_node_dependencies.py
- CI/integration_tests/test_class.py
- CI/integration_tests/test_example_01.py
- CI/integration_tests/test_graph_01.py
- CI/integration_tests/test_multiple_instances.py
- CI/integration_tests/test_numpy_params_results.py
- CI/integration_tests/test_passed_models.py
- CI/unit_tests/utlis/test_serializer.py
- zntrack/core/data_classes.py
- zntrack/zn/__init__.py
> Collection of small Bugfixes

- CI/integration_tests/dependencies/test_node_to_node_dependencies.py
- CI/integration_tests/test_no_dvc.py
- CI/integration_tests/test_params_types.py
- CI/integration_tests/test_stage_stage_dependency.py
- zntrack/core/decorator.py
- zntrack/core/zntrack.py
Allow for `MyNode()(no_dvc=True)`
- made an issue for the disabled test in #169
> Add `no_dvc` as `__call__` argument

- tests/integration_tests/test_zn_methods.py
> Close #155

- setup.py
- tests/integration_tests/test_zn_params.py
- tests/unit_tests/utlis/test_file_io.py
- zntrack/__init__.py
- zntrack/core/base.py
- zntrack/core/parameter.py
- zntrack/utils/file_io.py
- zntrack/zn/__init__.py
- add new `file_io.update_config_file` to update nested json/yaml files
- fix #187
> Code Cleanup

- tests/integration_tests/examples/test_example_01.py
- tests/integration_tests/examples/test_example_02.py
- tests/integration_tests/examples/test_example_03.py
- tests/integration_tests/examples/test_example_04.py
- tests/integration_tests/examples/test_example_05.py
- tests/integration_tests/examples/test_example_06.py
- tests/integration_tests/test_node_to_node_dependencies.py
- tests/integration_tests/test_options_save_n_load.py
- tests/integration_tests/test_single_node.py
- zntrack/core/base.py
- zntrack/core/dvcgraph.py
- zntrack/core/parameter.py
- zntrack/zn/__init__.py
- add tests for multiple run
- add ~~failing~~ test ~~to be fixed~~
- add `load_default` method which is called in the super init
> Fix Issues

- tests/integration_tests/test_dvc_outs.py
- tests/integration_tests/test_zn_methods.py
- zntrack/utils/serializer.py
> Fix `__main__` import issue with `zn.Methods`

- tests/integration_tests/test_zn_methods.py
- zntrack/zn/__init__.py
> fix lists for zn.methods

- tests/integration_tests/test_node_to_node_dependencies.py
- tests/unit_tests/core/test_dvcgraph.py
- zntrack/core/dvcgraph.py
> add tests and fix posix issue on windows

- tests/integration_tests/test_zn_methods.py
- zntrack/zn/__init__.py
> Optimize zn.Method serializer

- examples/docs/08_custom_zntrackoptions.ipynb
- tests/unit_tests/core/test_dvcgraph.py
- zntrack/core/base.py
- zntrack/core/dvcgraph.py
- zntrack/core/zntrackoption.py
- zntrack/dvc/__init__.py
- zntrack/metadata/base.py
- zntrack/utils/config.py
- zntrack/zn/__init__.py
- zntrack/zn/method.py
- zntrack/zn/plots.py
change `deps: str = "deps"` to `DEPS = enum.auto()`
> use enum library

- tests/integration_tests/function_wrapper/test_single_function.py
- tests/unit_tests/core/test_decorator.py
- tests/unit_tests/core/test_dvcgraph.py
- tests/unit_tests/utlis/test_utils.py
- zntrack/core/dvcgraph.py
- zntrack/core/functions/decorator.py
- zntrack/utils/utils.py
- clean up the `@nodify` code a bit
- combine methods into functions together with the `Node` inheritance
- add tests
- add support for `dotdict` for all `@nodify` options
> add `prepare_dvc_script` for `nodify` and `Node`

- LICENSE
- README.md
- setup.py
- zntrack/__init__.py
- zntrack/core/__init__.py
- zntrack/core/base.py
- zntrack/core/functions/__init__.py
- zntrack/core/functions/decorator.py
- zntrack/core/zntrackoption.py
- zntrack/dvc/__init__.py
- zntrack/interface/__init__.py
- zntrack/interface/base.py
- zntrack/metadata/__init__.py
- zntrack/metadata/base.py
- zntrack/metadata/decorators.py
- zntrack/project/__init__.py
- zntrack/project/zntrack_project.py
- zntrack/utils/__init__.py
- zntrack/utils/config.py
- zntrack/utils/decorators.py
- zntrack/utils/exceptions.py
- zntrack/utils/serializer.py
- zntrack/utils/utils.py
- zntrack/zn/__init__.py
- zntrack/zn/split_option.py
Change License to `License :: OSI Approved :: Apache Software License` and update the version to `0.4.0`
> Update License and bump version

- requirements.txt
- tests/integration_tests/test_node_to_node_dependencies.py
- tests/unit_tests/core/test_dvcgraph.py
- zntrack/core/dvcgraph.py
- fix getdeps issue
- bump required znjson version
> Fix getdeps issue

- examples/docs/04_metrics_and_plots.ipynb
- tests/integration_tests/test_zn_plots.py
- zntrack/core/dvcgraph.py
- zntrack/core/zntrackoption.py
- zntrack/descriptor/__init__.py
- zntrack/dvc/__init__.py
- zntrack/dvc/custom_base.py
- zntrack/zn/plots.py
add keyword argument support for `dvc plots modify` in the ZnTrackOption
> add support for `plots modify`

- tests/integration_tests/test_node_to_node_dependencies.py
- tests/unit_tests/core/test_dvcgraph.py
- tests/unit_tests/zn/test_zn_hash.py
- zntrack/core/base.py
- zntrack/core/dvcgraph.py
- zntrack/core/zntrackoption.py
- zntrack/zn/__init__.py
- zntrack/zn/zn_hash.py
- add `__hash__`
- add `zn.Hash` to generate an output file if it is required and no other output files are generated.
> add `__hash__()` based on the parameters and node_name

- tests/integration_tests/test_getdeps.py
- zntrack/zn/dependencies.py
Add `get_origin` to gain access to the `NodeAttribute` of a `zn.deps` instead of the actual values
> add `get_origin`

- poetry.lock
- pyproject.toml
- Add `pygit2` restriction due to installation candidate issues (should be removed in the future)
> change python dependency from `<3.11` to `<4.0.0`

- tests/integration_tests/test_zn_nodes2.py
- tests/unit_tests/core/test_core_base.py
- tests/unit_tests/core/test_dvcgraph.py
- zntrack/core/base.py
- zntrack/zn/nodes.py
- zntrack/zn/plots.py
> fix `zn.Nodes` issue with `zn.plots`

- tests/unit_tests/core/test_core_base.py
- tests/unit_tests/utils/test_helpers.py
- zntrack/core/base.py
- zntrack/utils/helpers.py
- zntrack/zn/nodes.py
- change getitem command
- improve error messages
> Small Code Updates

- README.md
see https://github.com/zincware/MDSuite/pull/584
> Add zincware badge

- tests/integration/test_none_values.py
- zntrack/fields/field.py
- zntrack/fields/zn/__init__.py
> Fix issue with `zn.nodes`

- examples/docs/parameter_optimization.ipynb
- tests/integration/test_project.py
- additional tests
- freeze optuna seed
> Additional tests

- poetry.lock
- pyproject.toml
- tests/integration/test_project.py
- zntrack/core/node.py
- zntrack/project/zntrack_project.py
- zntrack/utils/__init__.py
Update to new znflow release to support groups
> Use znflow groups

- tests/files/dvc_config/dataclass_deps.yaml
- tests/files/params_config/dataclass_deps.yaml
- tests/files/test_dataclass_deps.py
- tests/files/zntrack_config/dataclass_deps.json
- tests/integration/test_deps_dataclass.py
- zntrack/converter.py
- zntrack/plugins/dvc_plugin/__init__.py
- zntrack/project.py
Ensure that changes in the module without changes in the parameters triggers a re-run.
> fix dataclass module changing in `deps`

- tests/integration/test_file_changes.py
- tests/integration/test_from_rev.py
- tests/integration/test_lazy_loading.py
- tests/integration/test_node_node.py
- tests/integration/test_none_values.py
- tests/integration/test_project.py
- tests/integration/test_restarts.py
- tests/integration/test_single_node.py
- tests/integration/test_zn_nodes2.py
- tests/integration/test_zn_plots.py
- tests/integration/test_zntrack_deps.py
- tests/unit_tests/test_deps_types.py
- tests/unit_tests/test_node_init.py
- tests/unit_tests/test_node_load.py
- zntrack/examples/__init__.py
- zntrack/exceptions.py
- zntrack/from_rev.py
- zntrack/node.py
- zntrack/options.py
- zntrack/plugins/base.py
- zntrack/plugins/dvc_plugin/__init__.py
- zntrack/state.py
This PR fixes some legacy tests and introduces some new ones
> fix legacy tests

- tests/files/dvc_config/add.yaml
- tests/files/dvc_config/apply.yaml
- tests/files/dvc_config/basic.yaml
- tests/files/dvc_config/combined_dependencies.yaml
- tests/files/dvc_config/custom_field.yaml
- tests/files/dvc_config/custom_module.yaml
- tests/files/dvc_config/dataclass_deps.yaml
- tests/files/dvc_config/dependencies.yaml
- tests/files/dvc_config/groups.yaml
- tests/files/dvc_config/meta_params.yaml
- tests/files/dvc_config/metrics_deps.yaml
- tests/files/dvc_config/names.yaml
- tests/files/dvc_config/plots.yaml
- tests/files/dvc_config/user_config.yaml
- tests/files/test_basic.py
- tests/files/test_user_config.py
- tests/integration/test_project.py
- zntrack/config.py
- zntrack/project.py
During `project.build()` check for all `node-meta.json` and see if they are in the git repo. If so, raise an Error message.
> change `ALWAYS_CACHE=True` default

- tests/benchmark/test_benchmark.py
- tests/files/test_groups.py
- zntrack/node.py
- zntrack/project.py
> use better scaling name generator

- docs/source/node_details.rst
- tests/files/test_dataclass_w_deps_params_path.py
- tests/files/zntrack_config/dataclass_w_deps_params_path.json
- tests/integration/test_deps_dataclass.py
- uv.lock
- zntrack/converter.py
> fix `zntrack.fields` in dataclass off graph nodes reconstruction
